[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  BUN_VERSION = "1"

[[redirects]]
  from = "/install.sh"
  to = "https://raw.githubusercontent.com/wilfredinni/noodle/main/scripts/install.sh"
  status = 301

[[headers]]
  for = "/update.json"
  [headers.values]
    Cache-Control = "s-maxage=300, stale-while-revalidate=600"
