[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  BUN_VERSION = "1"

[[redirects]]
  from = "/install.sh"
  to = "https://raw.githubusercontent.com/wilfredinni/noodle/main/scripts/install.sh"
  status = 301
